
language: node_js
node_js:
  - "lts/*"

before_install:
  - openssl aes-256-cbc -K $encrypted_440e77bfda4d_key -iv $encrypted_440e77bfda4d_iv -in donnelson-sandbox-687eb49c0e08.json.enc -out donnelson-sandbox-687eb49c0e08.json -d

install:
  - npm install

script:
  - npm run build

before_deploy:
  # Remove unused files and dirs
  - rm -rf ./client
  - rm -rf ./server
  - rm package.json package-lock.json
  # Move the dist directory to root
  - mv ./dist/* .

deploy:
  edge: true
  provider: gae
  skip_cleanup: true
  keyfile: "donnelson-sandbox-687eb49c0e08.json"
  project: "donnelson-sandbox"

 
# Run Travis CLI in this repo
# gem install travis

# Delete Travis Cache
# travis cache --com
# travis cache --com --delete

# Encrypt Secure Variables
# gem install travis
# travis login --github-token replace_with_github_personal_token
# travis enable
# cd to/this/repo
# travis encrypt-file donnelson-sandbox-687eb49c0e08.json
